name: ğŸš€ Deploy website on push via ftp to app.headtracker.net

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
jobs:
  build:
    name: ğŸ—ï¸ Build and ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --deploy-url=https://app.headtracker.net

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.WEBUI_SERVER }}
          username: ${{ secrets.WEBUI_FTP_USERNAME }}
          password: ${{ secrets.WEBUI_FTP_PASSWORD }}
          local-dir: dist/headtracker-webui/browser

